spring:
  application:
    name: client
  cloud:
    consul:
      host: 0.0.0.0
      port: 8500
      discovery:
        register: false #Decidimos si queremos que la app se registre o no en el servidor de Consul

